Repository osbuild/bootc-image-builder, pull requests merged in 2024-04, with the labels that each got.

#200 add doc on cross-arch builds
  README.md
Labels: Stale

#379 test: enable iso installer tests for both centos/fedora
  test/test_build.py
  test/testcases.py
Labels: :open_mouth: IMPORTANT

#382 test: Make sure that the osbuild store exists
  test/test_build.py
Labels: :open_mouth: IMPORTANT

#355 Fix passing the --tls-verify flag to podman pull
  bib/cmd/bootc-image-builder/main.go
  test/containerbuild.py
  test/test_opts.py
Labels: :open_mouth: IMPORTANT

#385 container: fix crash when `Container.New()` defer() is run
  bib/internal/container/container.go
  bib/internal/container/container_test.go
Labels: :open_mouth: IMPORTANT

#390 test: add smoke test that checks that --log-level is honored
  test/test_opts.py
Labels: :baby_bottle: Simple
